entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: "https"
          permanent: true
  websecure:
    address: ":443"

certificatesResolvers:
  cloudflare:
    acme:
      email: "delwinmathew2004@gmail.com" # Replace with your email
      storage: "/acme.json"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

log:
  level: DEBUG

# Enable the file provider to load dynamic configurations
providers:
  file:
    filename: "/etc/traefik/dynamic.yml"

# API and dashboard configuration
api:
  dashboard: true
  insecure: true  # Set to false in production and use proper authentication
  